spring:
  profiles:
    include: base
  jackson.date-format: yyyy-MM-dd HH:mm:ss
  jackson.time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/qd-mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    password: 123456
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1
        max-idle: 8
    port: 6379
  # 路由网关配置
  cloud:
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略，通过serviceId 路由到指定的服务，请求需要带服务id  比如 localhost:8888/qd-mall-usercenter/xxx/xxx
      discovery:
        locator:
          enabled: true
          # 服务名称支持小写（如果是eureka注册中心 服务注册会将服务名改为大写，这个配置就是忽略服务名请求的大小写，但是我们是用nacos 不会改变服务名的大小写，所以不需要考虑这个问题）
#          lower-case-service-id: true
      # 配置路由规则（路由、断言、过滤器）
      routes:
        # 1、用户中心
          # 采用自定义路由 ID（有固定用法，不同的 id 有不同的功能，详见：https://cloud.spring.io/spring-cloud-gateway/2.0.x/single/spring-cloud-gateway.html#gateway-route-filters）
        - id: QD-MALL-USERCENTER
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名 --- 这就是走的ribbon的负载策略（如果想改吧默认的负载策略，可以按照在配置文件指定ribbon的负载策略或者自定义）
          uri: lb://qd-mall-usercenter
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # Method 方法谓词，这里是匹配 GET 和 POST 请求 (路由断言)
            # path 路径谓词 匹配/sys-user/** 的,这里的路径匹配应该是类似于nginx的最大前缀匹配
            - Path=/qd-mall-usercenter/**
          default-filters:
            # 熔断处理配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/defaultfallback
        # 2、授权认证中心
        - id: QD-MALL-UAASRVER
          uri: lb://qd-mall-uaaserver
          predicates:
            # 路径匹配，前缀过滤，以/api/oauth开头的
            - Path=/uaa/api/oauth/**
            # 过滤规则，
          filters:
            # 去除请求路径前缀的接数，如本来请求为（需要加服务名）：http://localhost:8888/qd-mall-uaaserver/uaa/api/oauth/** 配置后直接：http://localhost:8888/qd-mall-uaaserver/api/oauth/**即可
            - StripPrefix=1
      # 3、消息服务中心
        - id: QD-MALL-MESSAGESRVER
          uri: lb://qd-mall-messageserver
          predicates:
          # 路径匹配，前缀过滤，以/api/oauth开头的
          - Path=/qd-mall-messageserver/**


mall:
  swagger:
    enabled: true
    title: 网关中心
    description: 网关中心接口文档
    version: 1.0
    base-package: com.qidian.mall.gateway.controller



# hystrix 3秒后自动超时触发熔断
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 1000
feign:
  hystrix:
    enabled: true


# #  整合spring boot admin + actuator 暴露端点，暴露路由信息，
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
# 配置日志级别，方别调试(指定日志文件输出位置，admin线上可以查看)
logging:
  level:
    org.springframework.cloud.gateway: debug
  file: D:/WorkSpace/qd-mall-all/logs/application/qd-mall-messageserver/qd-mall-messageserver.log