spring:
  profiles:
    include: base
  jackson.date-format: yyyy-MM-dd HH:mm:ss
  jackson.time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/qd-mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    password:
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1
        max-idle: 8
    port: 6379
  # 路由网关配置
  cloud:
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      # 配置路由规则
      routes:
        # 1、用户中心
          # 采用自定义路由 ID（有固定用法，不同的 id 有不同的功能，详见：https://cloud.spring.io/spring-cloud-gateway/2.0.x/single/spring-cloud-gateway.html#gateway-route-filters）
        - id: QD-MALL-USERCENTER
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
          uri: lb://qd-mall-usercenter
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # Method 方法谓词，这里是匹配 GET 和 POST 请求 (路由断言)
            - Method=GET,POST
        # 2、授权认证中心
        - id: QD-MALL-UAASRVER
          uri: lb://qd-mall-uaaserver
          predicates:
            # 路径匹配，前缀过滤，以/api/oauth开头的
            - Path=/api/oauth/**
            # 过滤规则，
          filters:
            # 去除请求路径前缀的接数，如本来请求为（需要加服务名）：http://localhost:8888/qd-mall-uaacenter/api/oauth/** 配置后直接http://localhost:8888/api/oauth/**即可
            - StripPrefix=1
mall:
  swagger:
    enabled: true
    title: 网关中心
    description: 网关中心接口文档
    version: 1.0
    base-package: com.qidian.mall.controller

# 配置日志级别，方别调试
logging:
  level:
    org.springframework.cloud.gateway: debug