spring:
  jackson.date-format: yyyy-MM-dd HH:mm:ss
  jackson.time-zone: GMT+8
  profiles:
    include: base
  redis:
    database: 0
    host: 127.0.0.1
    password: 123456
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1
        max-idle: 8
    port: 6379
# swagger配置、认证过滤请求配置
mall:
  swagger:
    enabled: true
    title: 消息服务中心
    description: 消息服务中心接口文档
    version: 1.0
    base-package: com.qidian.mall.message.sms.controller
    globalOperationParameters:
    - name: token
      description: token
      modelRef: string
      parameterType: header
      required: false
  security:
    ignore:
      httpUrls: >
        /sms-server/**


# 资源服务器对应认证服务器的客户端信息和端点配置
security:
  oauth2:
    client:
      client-id: zlt
      client-secret: zlt
      access-token-uri: http://localhost:8088/oauth/token
      user-authorization-uri: http://localhost:8088/oauth/authorize
    resource:
      token-info-uri: http://localhost:8088/oauth/check_token



# rocketMq 生产者配置
#rocketmq:
#  name-server: 192.168.0.110:9876;192.168.0.111:9876
#  producer:
#    group: my-group
#  # 消费者一般在其他业务模块
#  consumer:
#    group: my-group


# feign客户端,支持okhttp，开启熔断----谁调用谁开启
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 15000
# ribbon 相关配置（覆盖feign的超时配置）
ribbon:
  # 饥饿加载
  eager-load:
    enabled: true
  #  #说明：同一台实例的最大自动重试次数，默认为1次，不包括首次
  #  MaxAutoRetries: 1
  #  #说明：要重试的下一个实例的最大数量，默认为1，不包括第一次被调用的实例
  #  MaxAutoRetriesNextServer: 1
  #  #说明：是否所有的操作都重试，默认为true
  #  OkToRetryOnAllOperations: true
  #  #说明：从注册中心刷新服务器列表信息的时间间隔，默认为2000毫秒，即2秒
  #  ServerListRefreshInterval: 2000
  #说明：使用Apache HttpClient连接超时时间，单位为毫秒
  ConnectTimeout: 3000
  #说明：使用Apache HttpClient读取的超时时间，单位为毫秒
  ReadTimeout: 3000


#--------阿里云短信配置参数 start--------------#
aliyun:
  sms:
    # 认证相关 LTAI4G8qWFxhbeiMt3neriQH HpzjqBVp2WHBDtfQELDe54tsQpVmZc
    accessKeyId:
    accessKeySecret:
    #产品名称:云通信短信API产品,开发者无需替换
    product: Dysmsapi
    #产品域名,开发者无需替换
    domain: dysmsapi.aliyuncs.com
    regionId: cn-hangzhou
    #短信签名名称（国内/国际/港澳台消息-签名管理下面）
    signName: "奇点商城"
    #发送日期 支持30天内记录查询，格式yyyyMMdd
    dateFormat: yyyyMMdd
    #服务结点
    endpointName: cn-hangzhou
#--------阿里云短信配置参数 end--------------#


# 暴露端点，暴露路由信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  file: D:/WorkSpace/qd-mall-all/logs/application/qd-mall-messageserver/qd-mall-messageserver.log