spring:
  profiles:
    include: base
  jackson.date-format: yyyy-MM-dd HH:mm:ss
  jackson.time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/qd-mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  # 本地mac redis 没有密码，公司本地 123456
  redis:
    database: 0
    host: 127.0.0.1
    password: 123456
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1
        max-idle: 8
    port: 6379
  thymeleaf:
    prefix: classpath:/static/
# 配置token 的存储配置方式 jwt
mall:
  oauth2:
    token:
      store:
        type: authJwt
  # 配置忽略认证的请求
  security:
    ignore:
      # 忽略认证的地址
      httpUrls: >
        /api/oauth/**,
        /validata/**,
        /clients,
        /clients/**,
        /login.html,
        /css/**,
        /images/**,
        /js/**
    code:
      # 忽略验证码的应用编号---暂时没用
      ignoreClientCode: app
  swagger:
    enabled: true
    title: 认证中心
    description: 认证中心接口文档
    version: 1.0
    base-package: com.qidian.mall.uaa.controller

# 谁调用 feign客户端接口，谁配置开启熔断
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: true

# hystrix 相关配置：
# 如果开启熔断 需要配置信号量隔离，默认的线程隔离，会使feign拦截器 不能获取请求上下文和安全上下文的信息（threadLocal 置空） --- 后面使用sentine 替换看看
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 15000
# ribbon 相关配置（覆盖feign的超时配置）
ribbon:
  # 饥饿加载(配置那个服务端需要饥饿加载)
  eager-load:
    enabled: true
    clients: qd-mall-usercenter
  #  #说明：同一台实例的最大自动重试次数，默认为1次，不包括首次
#  MaxAutoRetries: 1
#  #说明：要重试的下一个实例的最大数量，默认为1，不包括第一次被调用的实例
#  MaxAutoRetriesNextServer: 1
#  #说明：是否所有的操作都重试，默认为true
#  OkToRetryOnAllOperations: true
#  #说明：从注册中心刷新服务器列表信息的时间间隔，默认为2000毫秒，即2秒
#  ServerListRefreshInterval: 2000
  #说明：使用Apache HttpClient连接超时时间，单位为毫秒
  ConnectTimeout: 3000
  #说明：使用Apache HttpClient读取的超时时间，单位为毫秒
  ReadTimeout: 3000

# 暴露端点，暴露路由信息，
management:
  endpoints:
    web:
      exposure:
        include: '*'