spring:
  jackson.date-format: yyyy-MM-dd HH:mm:ss
  jackson.time-zone: GMT+8
  datasource:
    # 192.168.0.109 本地虚拟机docker db （docker-compose部署）  本地mysql密码是root
    url: jdbc:mysql://localhost:3306/qd-mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    # 国际化配置
  messages:
    basename: i18n/messages
    encoding: UTF-8
  redis:
    database: 0
    host: 127.0.0.1
    password: 123456
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1
        max-idle: 8
    port: 6379
server:
    port: 9002
# springboot自带logback日志打印级别配置（默认info）--->spring-boot-starter-web依赖中包含了相关日志依赖
logging:
  level:
    root: INFO
    com:
      qidian:
        mall:
          mapper:
            SysUserMapper: debug
#      alibaba:
#        nacos:
#          client:
#            naming: warn
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.qidain.mall.entity

# httpclient配置
http:
  maxTotal: 100
  #并发数
  defaultMaxPerRoute: 20
  #创建连接的最长时间
  connectTimeout: 1000
  #从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
  #数据传输的最长时间
  socketTimeout: 10000
  #提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true
  waitTime: 3000
  idleConTime: 3
mall:
  swagger:
    enabled: true
    title: 用户中心
    description: 用户中心接口文档
    version: 1.0
    base-package: com.qidian.mall.controller
  cache-manager:
    configs:
      - key: menu
        second: 600
      - key: user
        second: 1800